bank/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bank_app/urls.py
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('form', views.form, name='form'),
    path('api/branches/<int:district_id>/', views.get_branches_by_district, name='get_branches_by_district'),
    path('welcome', views.welcome, name='welcome'),
    path('logout', views.logout, name='logout'),
]

bank_app/models.py
from django.db import models


# Create your models here.

class District(models.Model):
    district = models.CharField(max_length=250)
    wiki_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.district


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class UserData(models.Model):
    name = models.CharField(max_length=250)
    dob = models.DateField()
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    district = models.ForeignKey('District', on_delete=models.CASCADE)
    branch = models.ForeignKey('Branch', on_delete=models.CASCADE)
    account_type = models.CharField(max_length=150)
    material = models.CharField(max_length=200)

    def __str__(self):
        return self.name

bank_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import District, Branch, UserData


# Create your views here.

def home(request):
    districts = District.objects.all()
    return render(request, 'home.html', {'districts': districts})


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exist")
                return redirect('bank_app:register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                messages.info(request, "User created")
                return redirect('bank_app:login')
        else:
            messages.info(request, "Password doesn't match")
            return redirect('bank_app:register')

    return render(request, 'register.html')


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.info(request, "Success")
            return redirect('bank_app:welcome')
        else:
            messages.info(request, "Username or Password is wrong")
            return redirect('bank_app:login')

    return render(request, 'login.html')


def form(request):
    districts = District.objects.all()

    if request.method == "POST":
        name = request.POST.get('name', '')
        dob = request.POST.get('dob', '')
        age = request.POST.get('age', '')
        gender = request.POST.get('gender', '')
        phone = request.POST.get('phone_number', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address', '')
        district_id = request.POST['district']
        branch_id = request.POST['branch']
        account_type = request.POST.get('account_type', '')
        material = request.POST.get('material_provided', '')

        district = District.objects.get(pk=district_id)
        branch = Branch.objects.get(pk=branch_id)

        user_data = UserData(name=name, dob=dob, age=age, gender=gender, phone=phone, email=email, address=address,
                             district=district, branch=branch, account_type=account_type, material=material)
        user_data.save()
        messages.info(request, "Form created")

    return render(request, 'form.html', {'districts': districts})


def get_branches_by_district(request, district_id):
    try:
        district = District.objects.get(pk=district_id)
        branches = Branch.objects.filter(district=district)
        data = [{'id': branch.id, 'name': branch.name} for branch in branches]
        return JsonResponse(data, safe=False)
    except District.DoesNotExist:
        return JsonResponse([], safe=False)


def welcome(request):
    return render(request, 'welcome.html')


def logout(request):
    auth.logout(request)
    return redirect('bank_app:home')

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="An Banking website model">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>New-Gen Bank</title>
</head>
<body>

    <!--NAVBAR-->
    <div>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">New-Gens</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'bank_app:home' %}">Home</a>
                </li>

                  <li class="nav-item dropdown">
                  <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                      </button>
                      <ul class="dropdown-menu">
                          {% for i in districts %}
                            <li><a class="dropdown-item" href="{{i.wiki_url}}">{{i.district}}</a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </li>

              </ul>
              <form class="d-flex">
                  {% if user.is_authenticated %}
                  <p class="nav-item" style="padding-top: 15px;padding-right: 15px;">Hello {{user.username}}</p>
                  <div class="cred_btn">
                      <a class="btn btn-outline-danger" href="{% url 'bank_app:logout' %}">Log Out</a>
                  </div>
                  {% else %}
                  <div class="cred_btn">
                      <a class="btn btn-outline-success" href="{% url 'bank_app:register' %}">Register</a>
                  </div>
                  <div class="cred_btn">
                      <a class="btn btn-outline-success" href="{% url 'bank_app:login' %}">Log In</a>
                  </div>
                  {% endif %}
              </form>
            </div>
          </div>
        </nav>
    </div>

    {% block content %}
    {% endblock %}

    <!--FOOTER-->

    <footer class="bg-light text-center text-lg-start">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © <script>document.write(new Date().getFullYear())</script> Copyright:
        <a class="text-dark" href="">New-Gens</a>
      </div>
      <!-- Copyright -->
    </footer>


    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <section class="v-100" style="background-color: #eee; padding: 88px;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Form</p>

                <form method="post" action="" class="mx-1 mx-md-4" id="myForm">
                  {% csrf_token %}

                  <div>
                    {% for m in messages %}
                    <div class="alert alert-warning" role="alert">
<!--                      <small id="emailHelp" class="form-text text-muted text-center" style="display: block;">{{m}}</small>-->
                      <a href="{% url 'bank_app:home' %}" class="text-center" style="display: block;">Home</a>
                    </div>
                    {% endfor %}
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="name">Name</label>
                      <input type="text" id="name" class="form-control" name="name"
                        placeholder="Name" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="dob">Date of birth</label>
                      <input type="date" id="dob" class="form-control" name="dob"
                        placeholder="dd-mm-yy" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="age">Age</label>
                      <input type="text" id="age" class="form-control" name="age"
                        placeholder="Age" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <p class="form-label" >Gender</p>
                      <div class="container">
                        <input type="radio" id="male" name="fav_language" value="HTML">
                        <label for="male">Male</label><br>
                        <input type="radio" id="female" name="fav_language" value="CSS">
                        <label for="female">Female</label><br>
                        <input type="radio" id="other" name="fav_language" value="JavaScript">
                        <label for="other">Other</label>
                      </div>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="phone_number">Phone no</label>
                      <input type="tel" id="phone_number" class="form-control" name="phone_number"
                        placeholder="Phone no" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="email">Email address</label>
                      <input type="email" id="email" class="form-control" name="email"
                        placeholder="Email address" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="address">Address</label>
                      <textarea id="address" name="address" rows="4" cols="50"></textarea>
                      <br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="district">District</label>
                        <select class="form-control" id="district" name="district" required>
                          <option value="">Choose District</option>
                            {% for district in districts %}
                              <option value="{{district.id}}">{{district.district}}</option>
                            {% endfor %}
                        </select>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="branch">Branch</label>
                        <select class="form-control" id="branch" name="branch" required>
                          <option value="">Choose Branch</option>
                        </select>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="account_type">Account type</label>
                      <select class="form-control" id="account_type" name="account_type" required>
                        <option>----------</option>
                        <option>Savings Account</option>
                        <option>Current Account</option>
                        <option>NRI Account</option>
                      </select>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="address">Material Provided</label>
                      <div id="material_provided"><div>
                        <label for="material_provided_0"><input type="checkbox" name="material_provided" value="debit_card" id="material_provided_0">
                     Debit Card</label>

                    </div><div>
                        <label for="material_provided_1"><input type="checkbox" name="material_provided" value="credit_card" id="material_provided_1">
                     Credit Card</label>

                    </div><div>
                        <label for="material_provided_2"><input type="checkbox" name="material_provided" value="cheque_book" id="material_provided_2">
                     Cheque Book</label>

                    </div>
                    </div>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                  </div>

<!--                  <div>-->
<!--                    {% for m in messages %}-->
<!--                    <div class="alert alert-warning" role="alert">-->
<!--&lt;!&ndash;                      <small id="emailHelp" class="form-text text-muted text-center" style="display: block;">{{m}}</small>&ndash;&gt;-->
<!--                      <a href="{% url 'bank_app:home' %}" class="text-center" style="display: block;">Home</a>-->
<!--                    </div>-->
<!--                    {% endfor %}-->
<!--                  </div>-->

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--JAVA SCRIPT FOR DEPENDENT DROPDOWN-->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const districtSelect = document.getElementById('district');
        const branchSelect = document.getElementById('branch');

        districtSelect.addEventListener('change', function () {
            const districtId = districtSelect.value;
            fetch(`/api/branches/${districtId}/`)
                .then(response => response.json())
                .then(data => {
                    branchSelect.innerHTML = '<option value="">Choose Branch</option>';
                    data.forEach(branch => {
                        const option = document.createElement('option');
                        option.value = branch.id;
                        option.textContent = branch.name;
                        branchSelect.appendChild(option);
                    });
                })
                .catch(error => {
                    console.error('Error fetching branches:', error);
                });
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
       const form = document.getElementById("myForm");
       form.addEventListener("submit", function (event) {
           // event.preventDefault();  Prevent the default form submission
           alert("Form submitted successfully!");
           // You can also add additional logic here, like submitting the form data via AJAX
       });
   });

</script>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="v-100" style="background-color: #eee; padding: 21px;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <div>
                        <div>
                          <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">New-Gens</p>
                        </div>
                        <div>
                          <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">We're here to help you build a financially secure and prosperous future. Trust and prosperity are our core values and the foundation of your financial well-being. We'll support you every step of the way as you work towards a brighter future.</p>
                        </div>
                        <div>
                          <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Count on us as your reliable partner, offering unwavering assistance in achieving financial stability and prosperity. Rest easy knowing that we'll be there for you, providing steadfast support on your financial journey towards a brighter tomorrow.</p>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <section class="v-100" style="background-color: #eee; padding: 80px;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign In</p>

                <form method="post" action="" class="mx-1 mx-md-4">
                  {% csrf_token %}

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="username">Username</label>
                      <input type="text" id="username" class="form-control" name="username" required
                        placeholder="Enter your username" />
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="password">Password</label>
                      <input type="password" id="password" class="form-control" name="password" placeholder="Password" required/>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Log In</button>
                  </div>

                </form>

                <div>
                  {% for m in messages %}
                  <div class="alert alert-warning" role="alert">
                    <small id="emailHelp" class="form-text text-muted text-center" style="display: block;">{{m}}</small>
                  </div>
                  {% endfor %}
                </div>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="v-100" style="background-color: #eee; padding: 40px;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form method="post" action="" class="mx-1 mx-md-4">
                  {% csrf_token %}
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="username">Username</label>
                      <input type="text" id="username" class="form-control" name="username" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="password">Password</label>
                      <input type="password" id="password" class="form-control" name="password" required/>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="cpassword">Repeat your password</label>
                      <input type="password" id="cpassword" class="form-control" name="cpassword" required/>
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <input class="form-check-input me-2" type="checkbox" value="" id="term" required/>
                    <label class="form-check-label" for="term">
                      I agree all statements in <a href="#!">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Register</button>
                  </div>

		          <div>
                   {% for m in messages %}
                    <div class="alert alert-warning" role="alert">
                      <small id="emailHelp" class="form-text text-muted text-center" style="display: block;">{{m}}</small>
                    </div>
                   {% endfor %}
                  </div>

                </form>

                <div>

                </div>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <section class="v-100" style="background-color: #eee; padding: 100px;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <div>
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Welcome, please fill out the form.</p>
                  <button class="text-center" style="border: none; margin-left: 160px;"><a  href="{% url 'bank_app:form' %}" class="btn btn-success text-center">FORM</a></button>
                </div>

                <div>
                  {% for m in messages %}
                  <div class="alert alert-warning" role="alert">
                    <small id="emailHelp" class="form-text text-muted text-center" style="display: block;">{{m}}</small>
                  </div>
                  {% endfor %}
                </div>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}